- name: Install Apache Web Server
  hosts: all
  become: yes
  tasks:
  
    - name: Install httpd
      apt:
        name: apache2
        state: present

    - name: Start and enable httpd service
      systemd:
        name: apache2
        state: started
        enabled: yes
