- name: Install Apache Web Server
  hosts: all
  become: yes
  tasks:
  
  - name: Install httpd
    yum:
      name: httpd
    state: present

  - name: Start and enable httpd service
    systemd:
      name: httpd
      state: started
      enabled: yes